### PR TITLE
Handle all StfErrors

### LINKED ISSUE #1274: StfError in trusted_call fails silently
https://github.com/litentry/litentry-parachain/blob/ce0ff808b44c204149da4c395734e0dc10fbabe9/tee-worker/app-libs/stf/src/trusted_call_litentry.rs#L125-L126

The trusted_call doesn't return to Parachain when an error happens, as the StfError is just emitted into the worker log.

Parachain needs to know when there is a trusted_call error.

### PR DESCRIPTION
**Pull request by Kailai-Wang**
resolves #1274

This PR tries to:
- handle all potential StfErrors to ensure they are propagated to the parachain.
- refactor the error handling a bit to avoid duplicate code

**Another important note:**

IMO we need to guarantee the stf execution always returns Ok() with extrinsic status `success`, otherwise it will be removed silently from the top pool, which might cause a state mismatch during sidechain block import for other workers. 
Please check the comments in `tee-worker/app-libs/stf/src/trusted_call.rs`, discussions are welcome.

### CODE REVIEW

File: tee-worker/app-libs/stf/src/trusted_call.rs [hunk 1]
```diff
@@ -219,6 +218,24 @@ where
...
+	//
+	// The execution will most likely fail again. However, the state could have been changed already by applying
+	// the state diff from the imported sidechain block. This could cause an inconsistent/mismatching state,
+	// for example, the nonce. See the nonce handling below: we increased the nonce no matter the STF is executed
+	// successfully or not.
+	//
+	// This is probably the reason why the nonce-handling test in `demo_shielding_unshielding.sh` sometimes fails.
+	//
+	// for now we should always return Ok(()) for this function and propagate the exe, at least for
+	// litentry STFs. I believe this is the right way to go, but it still needs more discussions.
```
Comment (BillyWooo) [inline tee-worker/app-libs/stf/src/trusted_call.rs:238]: Since we can't r/w storage async, e.g. IDGraphs, etc., I think this is the right way to go. 👍

**Review by BillyWooo — APPROVED** [review]
LGTM. Wait for the CI.

**Comment by jingleizhang** [comment]
Insightful thought for identifying the state inconsistent/mismatching issue.
