### PR TITLE
Fix assertion build panicked due to Uft8Error

### LINKED ISSUE #1397: assertion build panicked due to Uft8Error
Error logs:

`<unnamed>' panicked at 'called Result::unwrap() on an Err value: Utf8Error { valid_up_to: 2, error_len: Some(1) }', /home/ubuntu/repo/litentry-parachain/tee-worker/litentry/core/assertion-build/src/a4.rs:[2023-03-02T15:21:08Z INFO  integritee_service::ocall_bridge::sidechain_ocall] Enclave produced sidechain blocks: [17032]`

`fatal runtime error: failed to initiate panic, error
thread 'thread '<unnamed><unnamed>' panicked at '' panicked at 'called Result::unwrap() on an Err value: Sgx(SGX_ERROR_ENCLAVE_CRASHED)called Result::unwrap() on an Err value: Sgx(SGX_ERROR_ENCLAVE_CRASHED)', ', service/src/main.rsservice/src/main.rs::638499::8118
[2023-03-02T15:21:16Z ERROR integritee_service] Parentchain block syncing terminated with a failure: EnclaveApi(Sgx(SGX_ERROR_ENCLAVE_CRASHED))`

### PR DESCRIPTION
**Pull request by outofxxx**
resolved #1397

### CODE REVIEW

File: tee-worker/litentry/core/assertion-build/src/a11.rs [hunk 1]
```diff
@@ -60,30 +60,31 @@ pub fn build(
 
 		if let Identity::Evm { network, address } = id {
 			if matches!(network, EvmNetwork::Ethereum) {
-				let address = from_utf8(address.as_ref()).unwrap().to_string();
-				let addresses = vec![address];
+				if let Ok(addr) = from_utf8(address.as_ref()) {
```
Comment (Kailai-Wang) [inline tee-worker/litentry/core/assertion-build/src/a11.rs]: Do we need to pass it to parentchain instead of ignoring it? @jingleizhang 

I see something in https://github.com/litentry/litentry-parachain/blob/656c1985e6c682f34ae5d4a7dbc1ad0653d67acd/primitives/core/src/error.rs#L64-L65

Is this supposed to be used?

Comment (BillyWooo) [reply tee-worker/litentry/core/assertion-build/src/a11.rs]: Agree. I think we should propagate it out.

**Review by jingleizhang — COMMENTED** [review]
The Uft8Error should be propagated to parent chain.

File: tee-worker/litentry/core/assertion-build/src/a11.rs (hunk 1 above)
Comment (outofxxx) [reply tee-worker/litentry/core/assertion-build/src/a11.rs]: In those contexts(A4/A7/A10/A11) no need to propagate `ParseError` to parachain:
1. those payload are integer(Balance), return `ParseError` will be confusing.
2. in `from_utf8(address.as_ref())`, `address` is from `IDGraph`
3. we can add logs, if parse error.

Comment (jingleizhang) [reply tee-worker/litentry/core/assertion-build/src/a11.rs]: agree, some of ParseErrors are totally internal, and don't need to be propagated out

**Review by jingleizhang — APPROVED** [review]
Only the UTF8Error A8 needs to be propagated to parentchain as vcManagement.ParseError. LGTM.
