### PR TITLE
Upstream worker 3baa9159 pallets 75e57c5

### LINKED ISSUE #1687: Review the code difference to upstream once
### Context

Recently we have realised some **patches** might be incorrectly applied. Hence we'd like to revisit the codebase difference to upstream once just to be on the safe side.

Basically we need to:
- generate the diff between upstream codebase and ours
- review the code difference to make sure all changes are litentry-specific, and we don't miss any critical parts from upstream

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

### PR DESCRIPTION
**Pull request by BillyWooo**
as title
sync to upstream worker and pallets

resolves #1687

### CODE REVIEW

File: pallets/teerex/src/lib.rs [hunk 1]
```diff
@@ -76,6 +76,7 @@ pub mod pallet {
 		type Currency: Currency<<Self as frame_system::Config>::AccountId>;
 		type MomentsPerDay: Get<Self::Moment>;
 		type WeightInfo: WeightInfo;
+		type MaxSilenceTime: Get<Self::Moment>;
```
Comment (Kailai-Wang) [inline pallets/teerex/src/lib.rs:79]: I don't see where this is used, do we miss any upstream changes?

File: tee-worker/core-primitives/attestation-handler/src/attestation_handler.rs
Comment (Kailai-Wang) [inline tee-worker/core-primitives/attestation-handler/src/attestation_handler.rs:1]: FYI @zhouhuitian 

Loggings in this file are changed back to match the upstream - if you do need to use a customised logging format, please submit a PR.

File: tee-worker/service/src/ocall_bridge/worker_on_chain_ocall.rs [hunk 2]
```diff
@@ -44,10 +44,12 @@ impl<E, F> WorkerOnChainOCall<E, F> {
 
 impl<E, F> WorkerOnChainBridge for WorkerOnChainOCall<E, F>
 where
-	E: EnclaveBase,
-	F: CreateNodeApi,
+	E: EnclaveBase + std::marker::Send + std::marker::Sync,
+	F: CreateNodeApi + std::marker::Send + std::marker::Sync + 'static,
```
Comment (Kailai-Wang) [inline tee-worker/service/src/ocall_bridge/worker_on_chain_ocall.rs]: Why do we need this?

File: tee-worker/service/src/ocall_bridge/component_factory.rs [hunk 3]
```diff
@@ -128,7 +128,7 @@ impl<
 		TokioHandle,
 		MetricsReceiver,
 	> where
-	NodeApi: CreateNodeApi + 'static,
+	NodeApi: CreateNodeApi + 'static + std::marker::Send + std::marker::Sync,
```
Comment (Kailai-Wang) [inline tee-worker/service/src/ocall_bridge/component_factory.rs]: same below

File: tee-worker/service/src/worker.rs [hunk 4]
```diff
@@ -151,7 +151,6 @@ where
 			// FIXME: This is temporary only, as block broadcasting should be moved to trusted ws server.
 			let enclave_url = enclave.url.clone();
 			let worker_api_direct = DirectWorkerApi::new(enclave.url);
-			// related issue: https://github.com/litentry/litentry-parachain/issues/1124#issuecomment-1367690264
```
Comment (Kailai-Wang) [inline tee-worker/service/src/worker.rs]: I think we still need this comment to not forget about it (I'm not sure if it's resolved yet)

**Review by Kailai-Wang — COMMENTED** [review]
I just skimmed through the files and left comments on some questionable points, too many files :(

File: pallets/teerex/src/lib.rs (hunk 1 above)
Comment (BillyWooo) [reply pallets/teerex/src/lib.rs:79]: Yes, this is coming from upstream pallets.

File: tee-worker/service/src/ocall_bridge/worker_on_chain_ocall.rs (hunk 2 above)
Comment (BillyWooo) [reply tee-worker/service/src/ocall_bridge/worker_on_chain_ocall.rs]: Caused by build error: `F` cannot be sent between threads safely.

File: tee-worker/service/src/ocall_bridge/component_factory.rs (hunk 3 above)
Comment (BillyWooo) [reply tee-worker/service/src/ocall_bridge/component_factory.rs]: same as above 😂

File: tee-worker/service/src/ocall_bridge/worker_on_chain_ocall.rs (hunk 2 above)
Comment (Kailai-Wang) [reply tee-worker/service/src/ocall_bridge/worker_on_chain_ocall.rs]: You shouldn't need this tho - or why didn't we need that? What has changed?

File: pallets/teerex/src/lib.rs (hunk 1 above)
Comment (Kailai-Wang) [reply pallets/teerex/src/lib.rs:79]: But (I guess) it must be used somewhere, otherwise it doesn't make sense

File: tee-worker/core-primitives/node-api/factory/src/lib.rs [hunk 5]
```diff
@@ -20,7 +20,7 @@ use itp_api_client_types::{ParentchainApi, WsRpcClient};
 use sp_core::sr25519;
 
 /// Trait to create a node API, based on a node URL and signer.
-pub trait CreateNodeApi: Send + Sync + 'static {
+pub trait CreateNodeApi {
```
Comment (Kailai-Wang) [inline tee-worker/core-primitives/node-api/factory/src/lib.rs]: This is the reason : it should have been bound by  `Send + Sync + 'static` already -> similar to `EnclaveBase`

File: tee-worker/service/src/worker.rs (hunk 4 above)
Comment (BillyWooo) [reply tee-worker/service/src/worker.rs]: added back.

File: pallets/teerex/src/lib.rs (hunk 1 above)
Comment (BillyWooo) [reply pallets/teerex/src/lib.rs:79]: Originally, it's used inside `unregister_silent_workers` from upstream pallet code. We change the logic to use new parameter `heartbeat_timeout`. But in order to align with upstream, I added here.

**Review by Kailai-Wang — APPROVED** [review]
