### PR TITLE
Fix VC - A4 parse error Substrate address

### LINKED ISSUE #1453: VC:  A4 parse error Substrate address
0. set a user shielding key

1. link and verify an substrate account, using https://idh-alpha.litentry.io/

2. request VC A4, using https://idh-alpha.litentry.io/credential/lit-holder

then the error appears

image

### LINKED ISSUE #1473: Graphql crash occurs during IsHodlerOut unwrap
### Context

1. Running `tee-worke` in [dev hash](https://github.com/litentry/litentry-parachain/commit/0a1ddf4c1884fc89550631c7e2130cbf4ec017aa).
2. Run ts-test
```shell
yarn run test-identity:local
yarn run test-vc:local
```

---

[0m[38;5;8m[[0m2023-03-16T01:14:12Z [0m[34mDEBUG[0m lc_data_providers::graphql[0m[38;5;8m][0m check is_holder, credentials: {VerifiedCredentialsIsHodler(addresses:["ff93b45308fd417df303d6515ab04d9e89a750ca"], fromDate:"2017-01-01", network:ethereum, tokenAddress:"0xb59490aB09A0f526Cc7305822aC65f2Ab12f9723",minimumBalance:0.0){isHodler,address}}
[0m[38;5;8m[[0m2023-03-16T01:14:12Z [0m[34mDEBUG[0m itc_rest_client::http_client[0m[38;5;8m][0m uri: Uri { inner: "https://graph.tdf-labs.io/latest/graphql?query=%7BVerifiedCredentialsIsHodler%28addresses%3A%5B%22ff93b45308fd417df303d6515ab04d9e89a750ca%22%5D%2C+fromDate%3A%222017-01-01%22%2C+network%3Aethereum%2C+tokenAddress%3A%220xb59490aB09A0f526Cc7305822aC65f2Ab12f9723%22%2CminimumBalance%3A0.0%29%7BisHodler%2Caddress%7D%7D", scheme: RangeC { start: 0, end: 5 }, authority: Some(Authority { inner: "graph.tdf-labs.io", username: None, password: None, host: RangeC { start: 0, end: 17 }, port: None }), path: Some(RangeC { start: 25, end: 40 }), query: Some(RangeC { start: 41, end: 317 }), fragment: None }
[0m[38;5;8m[[0m2023-03-16T01:14:12Z [0m[34mDEBUG[0m itc_rest_client::http_client[0m[38;5;8m][0m no body to send
[0m[38;5;8m[[0m2023-03-16T01:14:12Z [0m[34mDEBUG[0m itc_rest_client::http_client[0m[38;5;8m][0m request: Request { inner: RequestBuilder { uri: Uri { inner: "https://graph.tdf-labs.io/latest/graphql?query=%7BVerifiedCredentialsIsHodler%28addresses%3A%5B%22ff93b45308fd417df303d6515ab04d9e89a750ca%22%5D%2C+fromDate%3A%222017-01-01%22%2C+network%3Aethereum%2C+tokenAddress%3A%220xb59490aB09A0f526Cc7305822aC65f2Ab12f9723%22%2CminimumBalance%3A0.0%29%7BisHodler%2Caddress%7D%7D", scheme: RangeC { start: 0, end: 5 }, authority: Some(Authority { inner: "graph.tdf-labs.io", username: None, password: None, host: RangeC { start: 0, end: 17 }, port: None }), path: Some(RangeC { start: 25, end: 40 }), query: Some(RangeC { start: 41, end: 317 }), fragment: None }, method: GET, version: Http11, headers: Headers({Ascii("connection"): "close", Ascii("Referer"): "https://graph.tdf-labs.io/latest/graphql?query=%7BVerifiedCredentialsIsHodler%28addresses%3A%5B%22ff93b45308fd417df303d6515ab04d9e89a750ca%22%5D%2C+fromDate%3A%222017-01-

[0m[38;5;8m[[0m2023-03-16T01:14:15Z [0m[34mDEBUG[0m itc_rest_client::rest_client[0m[38;5;8m][0m response headers: Headers({Ascii("ETag"): "W/\"1a1-yVP6VYSTQZ7c1NCyeHEzfnD2ipM\"", Ascii("Access-Control-Allow-Origin"): "*", Ascii("Content-Length"): "417", Ascii("Strict-Transport-Security"): "max-age=15724800; includeSubDomains", Ascii("X-Powered-By"): "Express", Ascii("Date"): "Thu, 16 Mar 2023 01:14:14 GMT", Ascii("Content-Type"): "application/json; charset=utf-8", Ascii("Connection"): "close"})
[0m[38;5;8m[[0m2023-03-16T01:14:15Z [0m[34mDEBUG[0m itc_rest_client::rest_client[0m[38;5;8m][0m response body: {"errors":[{"message":"GraphQL Error (Code: 401): {\"response\":{\"error\":\"Unauthorized\",\"status\":401,\"headers\":{}},\"request\":{\"query\":\"\\n{erc20Balance(\\n  address: \\\"ff93b45308fd417df303d6515ab04d9e89a750ca\\\", \\n  contract: \\\"0xb59490ab09a0f526cc7305822ac65f2ab12f9723\\\"\\n) {\\n  amount, decimals\\n}}\"}}","path":["VerifiedCredentialsIsHodler"]}],"data":{"VerifiedCredentialsIsHodler":null}}
[2023-03-16T01:14:15Z DEBUG ac_node_api::events] Decoding Event 'Teerex::ProcessedParentchainBlock'
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: null, expected a sequence", line: 0, column: 0)', /home/ztgx/codespace/litentry/litentry-parachain/tee-worker/litentry/core/data-providers/src/graphql.rs:204:84

' panicked at 'called `Result::unwrap()` on an `Err` value: Sgx(SGX_ERROR_ENCLAVE_CRASHED)', service/src/main.rs:639:81

[!] sync parentchain error: EnclaveApi(Sgx(SGX_ERROR_ENCLAVE_CRASHED)), websocket try to reconnect
[+] Received finalized header update (460), syncing parent chain...
[2023-03-16T01:20:35Z DEBUG ac_node_api::events] Decoding Event 'System::ExtrinsicSuccess'
[2023-03-16T01:20:35Z DEBUG itp_node_api_metadata::event] Decoded: phase = ApplyExtrinsic(0), pallet = "System" event = "ExtrinsicSuccess"
[2023-03-16T01:20:36Z ERROR integritee_service::sidechain_setup] Sgx(SGX_ERROR_ENCLAVE_CRASHED)
[2023-03-16T01:20:36Z DEBUG ac_node_api::events] Decoding Event 'System::ExtrinsicSuccess'
[2023-03-16T01:20:36Z DEBUG itp_node_api_metadata::event] Decoded: phase = ApplyExtrinsic(0), pallet = "System" event = "ExtrinsicSuccess"
[2023-03-16T01:20:37Z DEBUG ac_node_api::events] Decoding Event 'System::ExtrinsicSuccess'
[2023-03-16T01:20:37Z DEBUG itp_node_api_metadata::event] Decoded: phase = ApplyExtrinsic(0), pallet = "System" event = "ExtrinsicSuccess"
[2023-03-16T01:20:38Z DEBUG ac_node_api::events] Decoding Event 'System::ExtrinsicSuccess'
[2023-03-16T01:20:38Z DEBUG itp_node_api_metadata::event] Decoded: phase = ApplyExtrinsic(0), pallet = "System" event = "ExtrinsicSuccess"
[+] Found 380 block(s) to sync
[2023-03-16T01:20:39Z DEBUG ac_node_api::events] Decoding Event 'System::ExtrinsicSuccess'`
`

https://github.com/litentry/litentry-parachain/blob/0a1ddf4c1884fc89550631c7e2130cbf4ec017aa/tee-worker/litentry/core/data-providers/src/graphql.rs#L202-L205

### PR DESCRIPTION
**Pull request by outofxxx**
resolved #1453 
resolved #1473 

TODO：
- [x] The graphql's key seems to be invalid, the test has not passed, but there is a key in the Header.
- [x] ~~Running ts-test locally, there is a strange problem, After A1’s normal process, A2 did not trigger VCRequest,, and the VCIssued event directly started, so run it with CI to check the result.~~

image

### CODE REVIEW

File: tee-worker/litentry/core/assertion-build/src/a6.rs [hunk 1]
```diff
@@ -75,8 +75,8 @@ pub fn build(
 	}
 
 	info!("sum followers: {}", sum);
-	let min: u64;
-	let max: u64;
+	let min: u32;
```
Comment (BillyWooo) [inline tee-worker/litentry/core/assertion-build/src/a6.rs:78]: why change to u32?

**Review by BillyWooo — APPROVED** [review]
Generally, it looks good to me. Only one question.

File: tee-worker/litentry/core/assertion-build/src/a6.rs (hunk 1 above)
Comment (outofxxx) [reply tee-worker/litentry/core/assertion-build/src/a6.rs:78]: To keep the type consistent
