### PR TITLE
build_assertion error propagate to parachain

### LINKED ISSUE #1392: build_assertion error doesn't propagate to parachain
### Context

Repro-case:

- set user shielding key for "//Bob"
- request vc (e.g. A1) for "//Alice"

In tee-worker I see:
```
[2023-03-02T09:29:30Z DEBUG ita_stf::trusted_call_litentry] who "d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d", assertion A1
[2023-03-02T09:29:30Z ERROR ita_stf::trusted_call_litentry] user shielding key is missing, "d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d", A1
[2023-03-02T09:29:30Z ERROR itp_stf_executor::executor] Stf execute failed: AssertionBuildFail
```

which is good.
However, such error never arrives in parachain.

When I check the code, we never properly handle the errors:
https://github.com/litentry/litentry-parachain/blob/19951d385f70f3cb676653e22008638c4abdc234/tee-worker/app-libs/stf/src/trusted_call.rs#L601

Please also have ts-tests for this

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

### PR DESCRIPTION
**Pull request by outofxxx**
resolved #1392 

* remove `VCNotExists` from Event
* ts-test will check extrinsic' status, so remove it.

### CODE REVIEW

File: pallets/vc-management/src/lib.rs [hunk 1]
```diff
@@ -166,6 +166,12 @@ pub mod pallet {
 		#[pallet::weight(195_000_000)]
 		pub fn disable_vc(origin: OriginFor<T>, index: VCIndex) -> DispatchResultWithPostInfo {
 			let who = ensure_signed(origin)?;
+
+			if !VCRegistry::<T>::contains_key(index) {
+				Self::deposit_event(Event::VCNotExist { index });
+				return Ok(().into())
+			}
+
```
Comment (Kailai-Wang) [inline pallets/vc-management/src/lib.rs]: I don't think we need this, `try_mute` below already does the job.

Btw I think we should emit an error instead of the event in line #185 - F/E will be able to detect this as it's synchronous on-chain logic

File: pallets/vc-management/src/lib.rs [hunk 2]
```diff
@@ -189,6 +195,11 @@ pub mod pallet {
 		pub fn revoke_vc(origin: OriginFor<T>, index: VCIndex) -> DispatchResultWithPostInfo {
 			let who = ensure_signed(origin)?;
 
+			if !VCRegistry::<T>::contains_key(index) {
+				Self::deposit_event(Event::VCNotExist { index });
+				return Ok(().into())
+			}
+
```
Comment (Kailai-Wang) [inline pallets/vc-management/src/lib.rs]: same as above - `ok_or` below does the job already.

File: tee-worker/litentry/core/stf-task/receiver/src/handler/assertion.rs [hunk 3]
```diff
@@ -175,7 +177,11 @@ where
 			credential.add_proof(&sig, credential.issuance_block_number, &enclave_account);
 
 			if credential.validate().is_err() {
-				error!("failed to validate credential");
+				let error_msg = "failed to validate credential";
+				error!("	[BuildAssertion] : {}", error_msg);
+
+				self.on_failure(to_vcmp_error(error_msg));
```
Comment (Kailai-Wang) [inline tee-worker/litentry/core/stf-task/receiver/src/handler/assertion.rs:183]: calling `on_failure` within `on_success` sounds strange, can we have better handling? (ignore this if we can't)

**Review by Kailai-Wang — CHANGES_REQUESTED** [review]

File: tee-worker/litentry/core/stf-task/receiver/src/handler/assertion.rs (hunk 3 above)
Comment (outofxxx) [reply tee-worker/litentry/core/stf-task/receiver/src/handler/assertion.rs:183]: At first, I wanted to write another method to deal with such errors, but later I felt a little redundant because I felt that `on_failure` needs to handle all errors from `on_process` and `on_success`, so this method is not written, but directly call `on_failure` method in `on_success`. Please correct me if I understand this wrong.

Comment (Kailai-Wang) [reply tee-worker/litentry/core/stf-task/receiver/src/handler/assertion.rs:183]: Thanks - if we don't have better ways to handle it, let's just leave it as it is right now :)

File: pallets/vc-management/src/lib.rs (hunk 1 above)
Comment (0xverin) [reply pallets/vc-management/src/lib.rs]: https://polkadot.js.org/docs/api/cookbook/tx/#how-do-i-get-the-decoded-enum-for-an-extrinsicfailed-event

**Review by Kailai-Wang — APPROVED** [review]
Looks good to me, thanks
