### PR TITLE
Fix the sidechain metadata and type generation

### LINKED ISSUE #1672: Wrong metadata in tee-worker ts-tests
### Context

It seems the current [litentry-metadata.json](https://github.com/litentry/litentry-parachain/blob/93715df9c4da0290b6082a1e5552c6ffab53524c/tee-worker/ts-tests/litentry-metadata.json) was generated from an integritee-node. Additionally the generation command hooks with the 9944 port, which is wrong.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

### PR DESCRIPTION
**Pull request by Kailai-Wang**
resolves #1672 

It should give you the real sidechain metadata. The augmented types are re-generated too using `"@polkadot/typegen": "^9.14.2"`.

TODO:
- upgrade the polkadot/* package dependencies and re-generate the types (we might need some adjustments)
- #1673

### CODE REVIEW

File: tee-worker/core/rpc-client/src/mock.rs [hunk 1]
```diff
@@ -95,6 +95,10 @@ impl DirectApi for DirectClientMock {
 		RuntimeMetadataPrefixed::decode(&mut metadata.as_slice()).map_err(|e| e.into())
 	}
 
+	fn get_state_metadata_raw(&self) -> Result<String> {
+		unimplemented!()
```
Comment (kziemianek) [inline tee-worker/core/rpc-client/src/mock.rs:99]: Have you considered returning `self.metadata` or maybe we don't need this mock ?

**Review by kziemianek — APPROVED** [review]
I generated those types locally and recieved the same output.

File: tee-worker/core/rpc-client/src/mock.rs (hunk 1 above)
Comment (Kailai-Wang) [reply tee-worker/core/rpc-client/src/mock.rs:99]: I'm not aware it's used anywhere - so it's just to make it compile
