### PR TITLE
Fix the panic from WeightInfo in CI

### LINKED ISSUE #1414: Timeout in tee-test (demo-indirect-invocation)
### Context

https://github.com/litentry/litentry-parachain/actions/runs/4347876743
https://github.com/litentry/litentry-parachain/actions/runs/4347551085

Similar symptom, stalls after:
```
 send trusted call transfer from 5Dt1Wg85pXGLstt36t6TDdvXXoCtG6zkUL17KkyVaPYSrzGH to 5CCimpxmFnUWgLZ1G996QMZ1JPqdfnQCYxtcZngjDKDvLrPi: 2000000000000, nonce: 2
```

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

### PR DESCRIPTION
**Pull request by Kailai-Wang**
resolves #1414 

some other changes apart from the weights update:
- fix errors in `pallets/teeracle/src/benchmarking.rs` when benchmarking
- update self-hosted runner tag

Please note: we use upstream pallet weights instead of benchmarked weights for pallet-teerex, as we still have some upstream problems: https://github.com/integritee-network/pallets/issues/156

### CODE REVIEW

File: runtime/litmus/src/weights/mod.rs [hunk 1]
```diff
@@ -36,7 +36,8 @@ pub mod pallet_scheduler;
 pub mod pallet_session;
 pub mod pallet_sidechain;
 pub mod pallet_teeracle;
-pub mod pallet_teerex;
+// commented out due to upstream issue: https://github.com/integritee-network/pallets/issues/156
```
Comment (jingleizhang) [inline runtime/litmus/src/weights/mod.rs:39]: Good comment. Let's wait until they fix it.

**Review by jingleizhang — APPROVED** [review]
